/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ms.view;

/**
 *
 * @author TRANSDYN\ery
 */
public class HeaderRow extends javax.swing.JPanel {

    /**
     * Creates new form HeaderRow
     */
    public HeaderRow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfName = new javax.swing.JTextField();
        tfQuantity = new javax.swing.JTextField();
        tfType = new javax.swing.JTextField();
        tfAmount = new javax.swing.JFormattedTextField();
        tfPrice = new javax.swing.JFormattedTextField();
        tfNo = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setPreferredSize(new java.awt.Dimension(418, 20));

        tfName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfName.setText("Item Name");
        tfName.setFocusable(false);
        tfName.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tfName.setMinimumSize(new java.awt.Dimension(6, 19));
        tfName.setPreferredSize(new java.awt.Dimension(2, 20));
        tfName.setRequestFocusEnabled(false);

        tfQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfQuantity.setText("Quntity");
        tfQuantity.setFocusable(false);
        tfQuantity.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tfQuantity.setMinimumSize(new java.awt.Dimension(6, 19));
        tfQuantity.setPreferredSize(new java.awt.Dimension(2, 20));
        tfQuantity.setRequestFocusEnabled(false);

        tfType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfType.setText("T");
        tfType.setFocusable(false);
        tfType.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tfType.setPreferredSize(new java.awt.Dimension(8, 20));
        tfType.setRequestFocusEnabled(false);

        tfAmount.setEditable(false);
        tfAmount.setBackground(new java.awt.Color(255, 255, 255));
        tfAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.##"))));
        tfAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAmount.setText("Amount");
        tfAmount.setFocusable(false);
        tfAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfAmount.setRequestFocusEnabled(false);

        tfPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.##"))));
        tfPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPrice.setText("Price");
        tfPrice.setFocusable(false);
        tfPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfPrice.setPreferredSize(new java.awt.Dimension(69, 20));
        tfPrice.setRequestFocusEnabled(false);

        tfNo.setEditable(false);
        tfNo.setBackground(new java.awt.Color(255, 255, 255));
        tfNo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        tfNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNo.setText("No.");
        tfNo.setAutoscrolls(false);
        tfNo.setFocusable(false);
        tfNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfNo.setOpaque(false);
        tfNo.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tfType, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFormattedTextField tfAmount;
    public javax.swing.JTextField tfName;
    public javax.swing.JFormattedTextField tfNo;
    public javax.swing.JFormattedTextField tfPrice;
    public javax.swing.JTextField tfQuantity;
    public javax.swing.JTextField tfType;
    // End of variables declaration//GEN-END:variables
}
