/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ms.view;

import java.awt.Font;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author vmanchala
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        setUIFont(new javax.swing.plaf.FontUIResource("Verdana", Font.PLAIN, 11));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncustomerBill = new javax.swing.JButton();
        btnSearchItemDetails = new javax.swing.JButton();
        btnviewBills = new javax.swing.JButton();
        btnAddNewItem = new javax.swing.JButton();
        btnAddCollection = new javax.swing.JButton();
        btnViewCollection = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Information");
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setResizable(false);

        btncustomerBill.setText("Customer Bill");
        btncustomerBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustomerBillActionPerformed(evt);
            }
        });

        btnSearchItemDetails.setText("Search Item Details");
        btnSearchItemDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchItemDetailsActionPerformed(evt);
            }
        });

        btnviewBills.setText("View Bills");
        btnviewBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewBillsActionPerformed(evt);
            }
        });

        btnAddNewItem.setText("Add New Item");
        btnAddNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewItemActionPerformed(evt);
            }
        });

        btnAddCollection.setText("Add Collection");
        btnAddCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCollectionActionPerformed(evt);
            }
        });

        btnViewCollection.setText("View Collection");
        btnViewCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCollectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btncustomerBill)
                .addGap(5, 5, 5)
                .addComponent(btnSearchItemDetails)
                .addGap(5, 5, 5)
                .addComponent(btnviewBills)
                .addGap(5, 5, 5)
                .addComponent(btnAddNewItem)
                .addGap(5, 5, 5)
                .addComponent(btnAddCollection)
                .addGap(5, 5, 5)
                .addComponent(btnViewCollection)
                .addContainerGap(529, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncustomerBill)
                    .addComponent(btnSearchItemDetails)
                    .addComponent(btnviewBills)
                    .addComponent(btnAddNewItem)
                    .addComponent(btnAddCollection)
                    .addComponent(btnViewCollection))
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncustomerBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomerBillActionPerformed
        try {
            CustomerBill bill = new CustomerBill();
            bill.setVisible(true);
        } catch (SQLException ex) {
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btncustomerBillActionPerformed

    private void btnSearchItemDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchItemDetailsActionPerformed
        SearchItemDetails searchItem = new SearchItemDetails();
        searchItem.setVisible(true);
    }//GEN-LAST:event_btnSearchItemDetailsActionPerformed

    private void btnviewBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewBillsActionPerformed
        ViewBill viewBill = new ViewBill();
        viewBill.setVisible(true);
    }//GEN-LAST:event_btnviewBillsActionPerformed

    private void btnAddNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewItemActionPerformed
        ItemDetailsForm itemEntry = new ItemDetailsForm();
        itemEntry.setVisible(true);
    }//GEN-LAST:event_btnAddNewItemActionPerformed

    private void btnAddCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCollectionActionPerformed
       CollectionEntry collection = new CollectionEntry();
       collection.setVisible(true);
    }//GEN-LAST:event_btnAddCollectionActionPerformed

    private void btnViewCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCollectionActionPerformed
        ViewCollection viewCollection = new ViewCollection();
        viewCollection.setVisible(true);
    }//GEN-LAST:event_btnViewCollectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    private static void setUIFont(javax.swing.plaf.FontUIResource f) {
        java.util.Enumeration keys = UIManager.getDefaults().keys();
        while (keys.hasMoreElements()) {
            Object key = keys.nextElement();
            Object value = UIManager.get(key);
            if (value instanceof javax.swing.plaf.FontUIResource) {
                UIManager.put(key, f);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCollection;
    private javax.swing.JButton btnAddNewItem;
    private javax.swing.JButton btnSearchItemDetails;
    private javax.swing.JButton btnViewCollection;
    private javax.swing.JButton btncustomerBill;
    private javax.swing.JButton btnviewBills;
    // End of variables declaration//GEN-END:variables
}
