/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ms.view;

import com.ms.data.ItemDetails;
import com.ms.datafactory.CustomerDataFactory;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vmanchala
 */
public class UpdateItemDetails extends javax.swing.JDialog {

    /**
     * Creates new form UpdateItemDetails
     */
    private ItemDetails  itemDetails;
    public UpdateItemDetails(ItemDetails  itemDetails) {
        initComponents();
        this.itemDetails = itemDetails;
        tfItemNumber.setText(String.valueOf(itemDetails.getItemNo()));
        tfItemCode.setText(itemDetails.getItemCode());
        tfItemName.setText(itemDetails.getItemName());
        tfPurchasedPrice.setText(String.valueOf(itemDetails.getPurchasedRate()));
        tfItemPurchasedShop.setText(itemDetails.getPurchasedShop());
        tfItemSellPrice.setText(String.valueOf(itemDetails.getSellRate()));
        tfItemDetail.setText(itemDetails.getItemDetail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblItemNumber = new javax.swing.JLabel();
        lblItemCode = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        lblPurchasedPrice = new javax.swing.JLabel();
        lblItemPurchasedShop = new javax.swing.JLabel();
        lblItemSellPrice = new javax.swing.JLabel();
        lblItemDetail = new javax.swing.JLabel();
        tfItemDetail = new javax.swing.JTextField();
        tfItemSellPrice = new javax.swing.JFormattedTextField();
        tfItemPurchasedShop = new javax.swing.JTextField();
        tfPurchasedPrice = new javax.swing.JTextField();
        tfItemName = new javax.swing.JTextField();
        tfItemCode = new javax.swing.JTextField();
        tfItemNumber = new javax.swing.JFormattedTextField();
        btnInsertItem = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Item Details");

        lblItemNumber.setText("Item Number :");

        lblItemCode.setText("Item Priced Code :");

        lblItemName.setText("Item Name :");

        lblPurchasedPrice.setText("Purchased Price :");

        lblItemPurchasedShop.setText("Item Purchased Shop :");

        lblItemSellPrice.setText("Item Sell Price :");

        lblItemDetail.setText("Item Detail :");

        tfItemSellPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.###"))));

        tfItemNumber.setEditable(false);
        tfItemNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));

        btnInsertItem.setText("Update");
        btnInsertItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertItemActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblItemCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblItemName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPurchasedPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblItemPurchasedShop, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblItemSellPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblItemDetail, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfItemSellPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(tfItemPurchasedShop, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPurchasedPrice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfItemName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfItemCode, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfItemNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfItemDetail))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemNumber)
                    .addComponent(tfItemNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemCode)
                    .addComponent(tfItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemName)
                    .addComponent(tfItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPurchasedPrice)
                    .addComponent(tfPurchasedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemPurchasedShop)
                    .addComponent(tfItemPurchasedShop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemSellPrice)
                    .addComponent(tfItemSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemDetail)
                    .addComponent(tfItemDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertItem)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertItemActionPerformed
        try {            
            int itemNumber = Integer.valueOf(tfItemNumber.getValue().toString());
            itemDetails.setItemNo(itemNumber);
            itemDetails.setItemName(tfItemName.getText());
            itemDetails.setPurchasedRate(Float.valueOf(tfPurchasedPrice.getText()));
            itemDetails.setPurchasedShop(tfItemPurchasedShop.getText());
            float salePrice = Float.valueOf(tfItemSellPrice.getValue().toString());
            itemDetails.setSellRate(salePrice);
            itemDetails.setItemCode(tfItemCode.getText());
            itemDetails.setItemDetail(tfItemDetail.getText());
            int iresult = CustomerDataFactory.setItemDetails(itemDetails);
            if(iresult == 1) {
                JOptionPane.showMessageDialog(this, "Item Updated successfully", "Adding New Item", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                ItemDetailsForm itemDet = new ItemDetailsForm();
                itemDet.setVisible(true);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnInsertItemActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnInsertItem;
    private javax.swing.JLabel lblItemCode;
    private javax.swing.JLabel lblItemDetail;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemNumber;
    private javax.swing.JLabel lblItemPurchasedShop;
    private javax.swing.JLabel lblItemSellPrice;
    private javax.swing.JLabel lblPurchasedPrice;
    private javax.swing.JTextField tfItemCode;
    private javax.swing.JTextField tfItemDetail;
    private javax.swing.JTextField tfItemName;
    private javax.swing.JFormattedTextField tfItemNumber;
    private javax.swing.JTextField tfItemPurchasedShop;
    private javax.swing.JFormattedTextField tfItemSellPrice;
    private javax.swing.JTextField tfPurchasedPrice;
    // End of variables declaration//GEN-END:variables
}
